### ISSUE TITLE
Problem occur while retrieving data in Android platform

### ISSUE THREAD

**Issue by TerranceSon** [MOLPay/molpay-mobile-xdk-titanium#1]
Hi! I am running into the problem when trying to call module in my android device, but with the same code there is no any problem with IOS device. 
![screen shot 2017-06-22 at 3 54 40 pm](https://user-images.githubusercontent.com/11305335/27524466-427a2f3a-5a5f-11e7-9c20-3f1524197e77.png)

**Comment by clewlb** [comment]
@TerranceSon,

Thanks for the feedback. Please try again with our latest version 3.13.1

https://github.com/MOLPay/molpay-mobile-xdk-titanium/releases/tag/3.13.1

Thanks.
